# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Polygraphiae"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "The writings of Johannes Trithemius."

# Tagline below the site title
tagline: "Crypto means \"hidden\"."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://polygraphi.ae"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
#- text: Archives
#url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: nil

# Author information - author info at the bottom of the post
author_name: "Johannes Trithemius"
author_bio: "Aus Trittenheim"
author_url: "https://polygraphi.ae"
author_location: "Würzburg"
author_image: authorimage.jpg

# Footer ad banner
# banner_url: "https://justgoodthemes.com/"
# banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
#googleplus_username: "+username"
#github_username: "username"
#codepen_username: "username"
#dribbble_username: "username"
#medium_username: "@username"
#instagram_username: "username"
#pinterest_username: "username"
#linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
#paginate: 20
#paginate_path: '/blog/page:num/'
#plugins: [jekyll-paginate]

permalink: pretty
#markdown: kramdown
#kramdown:
#    auto_ids: false
